function [ys_, params, info] = news_bkw2012_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    Pi_=exp(params(6));
    kappa_=params(5)/2*(Pi_-1)^2;
    ys_(1)=1/(params(1)+params(2))*(log((1-params(10))*(1+params(5)*Pi_*(Pi_-1)*(1-params(3))/params(4)))-params(1)*log(1-kappa_-params(9)));
    ys_(2)=params(6);
    ys_(3)=0;
    ys_(4)=0;
    ys_(5)=params(6)+(-log(params(3)));
    % Auxiliary equations
ys_(6)=exo_(1);
ys_(7)=exo_(1);
ys_(8)=exo_(1);
ys_(9)=exo_(1);
ys_(10)=exo_(1);
ys_(11)=exo_(1);
ys_(12)=exo_(1);
ys_(13)=exo_(1);
ys_(14)=exo_(1);
ys_(15)=exo_(1);
ys_(16)=exo_(1);
ys_(17)=exo_(1);
ys_(18)=exo_(1);
ys_(19)=exo_(1);
ys_(20)=exo_(1);
ys_(21)=exo_(1);
ys_(22)=exo_(1);
ys_(23)=exo_(1);
ys_(24)=exo_(1);
    check_=0;
end
