function V = ValueFunctionAlwaysAtBorrowingConstraint( Av, beta, mu, rho, sigma, Ybar )
    % Ugly code generated by Maple
    t1 = (mu - Ybar - 1) * rho;
    t2 = 1 + Ybar;
    t3 = t2 ^ 2;
    t2 = 2 * t2;
    t4 = beta * rho;
    t5 = -1 + beta;
    t6 = -1 + beta * rho ^ 2;
    t7 = -1 + t4;
    t8 = 2 * t6;
    t5 = 1 / t5;
    t8 = 1 / t8;
    t6 = 1 / t6;
    t7 = 1 / t7;
    k0 = ((beta * (t4 * (t1 - mu - sigma) * (t1 - mu + sigma) + mu * (-t2 + mu) + rho * (mu * (t2 - 2 * mu) - t3 + rho * (mu ^ 2 - t3)) + sigma ^ 2) + t3) * t5 * t6 * t7) / 2;
    k1 = (1 + t4 * (t1 - mu) + Ybar) * t6 * t7;
    k2 = t8;
    
    V = k0 + k1 * Av + k2 * ( Av .* Av );
end