%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'news_SW03';
M_.dynare_version = '4.5-unstable';
oo_.dynare_version = '4.5-unstable';
options_.dynare_version = '4.5-unstable';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('news_SW03.log');
M_.exo_names = 'epsilon';
M_.exo_names_tex = 'epsilon';
M_.exo_names_long = 'epsilon';
M_.endo_names = 'mcf';
M_.endo_names_tex = 'mcf';
M_.endo_names_long = 'mcf';
M_.endo_names = char(M_.endo_names, 'zcapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcapf');
M_.endo_names_long = char(M_.endo_names_long, 'zcapf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'pkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkf');
M_.endo_names_long = char(M_.endo_names_long, 'pkf');
M_.endo_names = char(M_.endo_names, 'muf');
M_.endo_names_tex = char(M_.endo_names_tex, 'muf');
M_.endo_names_long = char(M_.endo_names_long, 'muf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'invef');
M_.endo_names_tex = char(M_.endo_names_tex, 'invef');
M_.endo_names_long = char(M_.endo_names_long, 'invef');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'labf');
M_.endo_names_tex = char(M_.endo_names_tex, 'labf');
M_.endo_names_long = char(M_.endo_names_long, 'labf');
M_.endo_names = char(M_.endo_names, 'pinff');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinff');
M_.endo_names_long = char(M_.endo_names_long, 'pinff');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'pf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pf');
M_.endo_names_long = char(M_.endo_names_long, 'pf');
M_.endo_names = char(M_.endo_names, 'emplf');
M_.endo_names_tex = char(M_.endo_names_tex, 'emplf');
M_.endo_names_long = char(M_.endo_names_long, 'emplf');
M_.endo_names = char(M_.endo_names, 'rrf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrf');
M_.endo_names_long = char(M_.endo_names_long, 'rrf');
M_.endo_names = char(M_.endo_names, 'effortf');
M_.endo_names_tex = char(M_.endo_names_tex, 'effortf');
M_.endo_names_long = char(M_.endo_names_long, 'effortf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'zcap');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcap');
M_.endo_names_long = char(M_.endo_names_long, 'zcap');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names_long = char(M_.endo_names_long, 'pk');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'inve');
M_.endo_names_tex = char(M_.endo_names_tex, 'inve');
M_.endo_names_long = char(M_.endo_names_long, 'inve');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'lab');
M_.endo_names_tex = char(M_.endo_names_tex, 'lab');
M_.endo_names_long = char(M_.endo_names_long, 'lab');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names_long = char(M_.endo_names_long, 'pinf');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'empl');
M_.endo_names_tex = char(M_.endo_names_tex, 'empl');
M_.endo_names_long = char(M_.endo_names_long, 'empl');
M_.endo_names = char(M_.endo_names, 'ww');
M_.endo_names_tex = char(M_.endo_names_tex, 'ww');
M_.endo_names_long = char(M_.endo_names_long, 'ww');
M_.endo_names = char(M_.endo_names, 'effort');
M_.endo_names_tex = char(M_.endo_names_tex, 'effort');
M_.endo_names_long = char(M_.endo_names_long, 'effort');
M_.endo_names = char(M_.endo_names, 'pinf4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf4');
M_.endo_names_long = char(M_.endo_names_long, 'pinf4');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'dr');
M_.endo_names_tex = char(M_.endo_names_tex, 'dr');
M_.endo_names_long = char(M_.endo_names_long, 'dr');
M_.endo_names = char(M_.endo_names, 'pinfLAG1');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfLAG1');
M_.endo_names_long = char(M_.endo_names_long, 'pinfLAG1');
M_.endo_names = char(M_.endo_names, 'pinfLAG2');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfLAG2');
M_.endo_names_long = char(M_.endo_names_long, 'pinfLAG2');
M_.endo_names = char(M_.endo_names, 'ygap');
M_.endo_names_tex = char(M_.endo_names_tex, 'ygap');
M_.endo_names_long = char(M_.endo_names_long, 'ygap');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'as');
M_.endo_names_tex = char(M_.endo_names_tex, 'as');
M_.endo_names_long = char(M_.endo_names_long, 'as');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'ls');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls');
M_.endo_names_long = char(M_.endo_names_long, 'ls');
M_.endo_names = char(M_.endo_names, 'qs');
M_.endo_names_tex = char(M_.endo_names_tex, 'qs');
M_.endo_names_long = char(M_.endo_names_long, 'qs');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'ms');
M_.endo_names_long = char(M_.endo_names_long, 'ms');
M_.endo_names = char(M_.endo_names, 'sinv');
M_.endo_names_tex = char(M_.endo_names_tex, 'sinv');
M_.endo_names_long = char(M_.endo_names_long, 'sinv');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'spinf');
M_.endo_names_long = char(M_.endo_names_long, 'spinf');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, 'sw');
M_.endo_names_long = char(M_.endo_names_long, 'sw');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kpf');
M_.endo_names_long = char(M_.endo_names_long, 'kpf');
M_.endo_names = char(M_.endo_names, 'habf');
M_.endo_names_tex = char(M_.endo_names_tex, 'habf');
M_.endo_names_long = char(M_.endo_names_long, 'habf');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp');
M_.endo_names_long = char(M_.endo_names_long, 'kp');
M_.endo_names = char(M_.endo_names, 'hab');
M_.endo_names_tex = char(M_.endo_names_tex, 'hab');
M_.endo_names_long = char(M_.endo_names_long, 'hab');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_0');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_1');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_2');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_3');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_4');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_5');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_6');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_7');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_8');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_9');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_10');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_11');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_11');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_12');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_12');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_13');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_13');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_14');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_14');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_15');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_15');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_16');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_16');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_17');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_17');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_18');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_18');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_18');
M_.param_names = 'calfa';
M_.param_names_tex = 'calfa';
M_.param_names_long = 'calfa';
M_.param_names = char(M_.param_names, 'ctou');
M_.param_names_tex = char(M_.param_names_tex, 'ctou');
M_.param_names_long = char(M_.param_names_long, 'ctou');
M_.param_names = char(M_.param_names, 'cbeta');
M_.param_names_tex = char(M_.param_names_tex, 'cbeta');
M_.param_names_long = char(M_.param_names_long, 'cbeta');
M_.param_names = char(M_.param_names, 'chab');
M_.param_names_tex = char(M_.param_names_tex, 'chab');
M_.param_names_long = char(M_.param_names_long, 'chab');
M_.param_names = char(M_.param_names, 'ccs');
M_.param_names_tex = char(M_.param_names_tex, 'ccs');
M_.param_names_long = char(M_.param_names_long, 'ccs');
M_.param_names = char(M_.param_names, 'cinvs');
M_.param_names_tex = char(M_.param_names_tex, 'cinvs');
M_.param_names_long = char(M_.param_names_long, 'cinvs');
M_.param_names = char(M_.param_names, 'csadjcost');
M_.param_names_tex = char(M_.param_names_tex, 'csadjcost');
M_.param_names_long = char(M_.param_names_long, 'csadjcost');
M_.param_names = char(M_.param_names, 'csigma');
M_.param_names_tex = char(M_.param_names_tex, 'csigma');
M_.param_names_long = char(M_.param_names_long, 'csigma');
M_.param_names = char(M_.param_names, 'chabb');
M_.param_names_tex = char(M_.param_names_tex, 'chabb');
M_.param_names_long = char(M_.param_names_long, 'chabb');
M_.param_names = char(M_.param_names, 'cprobw');
M_.param_names_tex = char(M_.param_names_tex, 'cprobw');
M_.param_names_long = char(M_.param_names_long, 'cprobw');
M_.param_names = char(M_.param_names, 'clandaw');
M_.param_names_tex = char(M_.param_names_tex, 'clandaw');
M_.param_names_long = char(M_.param_names_long, 'clandaw');
M_.param_names = char(M_.param_names, 'csigl');
M_.param_names_tex = char(M_.param_names_tex, 'csigl');
M_.param_names_long = char(M_.param_names_long, 'csigl');
M_.param_names = char(M_.param_names, 'cprobp');
M_.param_names_tex = char(M_.param_names_tex, 'cprobp');
M_.param_names_long = char(M_.param_names_long, 'cprobp');
M_.param_names = char(M_.param_names, 'cindw');
M_.param_names_tex = char(M_.param_names_tex, 'cindw');
M_.param_names_long = char(M_.param_names_long, 'cindw');
M_.param_names = char(M_.param_names, 'cindp');
M_.param_names_tex = char(M_.param_names_tex, 'cindp');
M_.param_names_long = char(M_.param_names_long, 'cindp');
M_.param_names = char(M_.param_names, 'cfc');
M_.param_names_tex = char(M_.param_names_tex, 'cfc');
M_.param_names_long = char(M_.param_names_long, 'cfc');
M_.param_names = char(M_.param_names, 'cinvdyn');
M_.param_names_tex = char(M_.param_names_tex, 'cinvdyn');
M_.param_names_long = char(M_.param_names_long, 'cinvdyn');
M_.param_names = char(M_.param_names, 'czcap');
M_.param_names_tex = char(M_.param_names_tex, 'czcap');
M_.param_names_long = char(M_.param_names_long, 'czcap');
M_.param_names = char(M_.param_names, 'csadjlab');
M_.param_names_tex = char(M_.param_names_tex, 'csadjlab');
M_.param_names_long = char(M_.param_names_long, 'csadjlab');
M_.param_names = char(M_.param_names, 'crpi');
M_.param_names_tex = char(M_.param_names_tex, 'crpi');
M_.param_names_long = char(M_.param_names_long, 'crpi');
M_.param_names = char(M_.param_names, 'crdpi');
M_.param_names_tex = char(M_.param_names_tex, 'crdpi');
M_.param_names_long = char(M_.param_names_long, 'crdpi');
M_.param_names = char(M_.param_names, 'crr');
M_.param_names_tex = char(M_.param_names_tex, 'crr');
M_.param_names_long = char(M_.param_names_long, 'crr');
M_.param_names = char(M_.param_names, 'cry');
M_.param_names_tex = char(M_.param_names_tex, 'cry');
M_.param_names_long = char(M_.param_names_long, 'cry');
M_.param_names = char(M_.param_names, 'crdy');
M_.param_names_tex = char(M_.param_names_tex, 'crdy');
M_.param_names_long = char(M_.param_names_long, 'crdy');
M_.param_names = char(M_.param_names, 'crhoa');
M_.param_names_tex = char(M_.param_names_tex, 'crhoa');
M_.param_names_long = char(M_.param_names_long, 'crhoa');
M_.param_names = char(M_.param_names, 'crhoas');
M_.param_names_tex = char(M_.param_names_tex, 'crhoas');
M_.param_names_long = char(M_.param_names_long, 'crhoas');
M_.param_names = char(M_.param_names, 'crhob');
M_.param_names_tex = char(M_.param_names_tex, 'crhob');
M_.param_names_long = char(M_.param_names_long, 'crhob');
M_.param_names = char(M_.param_names, 'crhog');
M_.param_names_tex = char(M_.param_names_tex, 'crhog');
M_.param_names_long = char(M_.param_names_long, 'crhog');
M_.param_names = char(M_.param_names, 'crhols');
M_.param_names_tex = char(M_.param_names_tex, 'crhols');
M_.param_names_long = char(M_.param_names_long, 'crhols');
M_.param_names = char(M_.param_names, 'crhoqs');
M_.param_names_tex = char(M_.param_names_tex, 'crhoqs');
M_.param_names_long = char(M_.param_names_long, 'crhoqs');
M_.param_names = char(M_.param_names, 'cscaleea');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleea');
M_.param_names_long = char(M_.param_names_long, 'cscaleea');
M_.param_names = char(M_.param_names, 'cscaleeas');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeas');
M_.param_names_long = char(M_.param_names_long, 'cscaleeas');
M_.param_names = char(M_.param_names, 'cscaleeb');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeb');
M_.param_names_long = char(M_.param_names_long, 'cscaleeb');
M_.param_names = char(M_.param_names, 'cscaleeg');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeg');
M_.param_names_long = char(M_.param_names_long, 'cscaleeg');
M_.param_names = char(M_.param_names, 'cscaleels');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleels');
M_.param_names_long = char(M_.param_names_long, 'cscaleels');
M_.param_names = char(M_.param_names, 'cscaleeqs');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeqs');
M_.param_names_long = char(M_.param_names_long, 'cscaleeqs');
M_.param_names = char(M_.param_names, 'cscaleem');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleem');
M_.param_names_long = char(M_.param_names_long, 'cscaleem');
M_.param_names = char(M_.param_names, 'cscaleeinv');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeinv');
M_.param_names_long = char(M_.param_names_long, 'cscaleeinv');
M_.param_names = char(M_.param_names, 'cscaleepinf');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleepinf');
M_.param_names_long = char(M_.param_names_long, 'cscaleepinf');
M_.param_names = char(M_.param_names, 'cscaleew');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleew');
M_.param_names_long = char(M_.param_names_long, 'cscaleew');
M_.param_names = char(M_.param_names, 'cscaleer');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleer');
M_.param_names_long = char(M_.param_names_long, 'cscaleer');
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 71;
M_.param_nbr = 41;
M_.orig_endo_nbr = 52;
M_.aux_vars(1).endo_index = 53;
M_.aux_vars(1).type = 3;
M_.aux_vars(1).orig_index = 1;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(2).endo_index = 54;
M_.aux_vars(2).type = 3;
M_.aux_vars(2).orig_index = 1;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(3).endo_index = 55;
M_.aux_vars(3).type = 3;
M_.aux_vars(3).orig_index = 1;
M_.aux_vars(3).orig_lead_lag = -2;
M_.aux_vars(4).endo_index = 56;
M_.aux_vars(4).type = 3;
M_.aux_vars(4).orig_index = 1;
M_.aux_vars(4).orig_lead_lag = -3;
M_.aux_vars(5).endo_index = 57;
M_.aux_vars(5).type = 3;
M_.aux_vars(5).orig_index = 1;
M_.aux_vars(5).orig_lead_lag = -4;
M_.aux_vars(6).endo_index = 58;
M_.aux_vars(6).type = 3;
M_.aux_vars(6).orig_index = 1;
M_.aux_vars(6).orig_lead_lag = -5;
M_.aux_vars(7).endo_index = 59;
M_.aux_vars(7).type = 3;
M_.aux_vars(7).orig_index = 1;
M_.aux_vars(7).orig_lead_lag = -6;
M_.aux_vars(8).endo_index = 60;
M_.aux_vars(8).type = 3;
M_.aux_vars(8).orig_index = 1;
M_.aux_vars(8).orig_lead_lag = -7;
M_.aux_vars(9).endo_index = 61;
M_.aux_vars(9).type = 3;
M_.aux_vars(9).orig_index = 1;
M_.aux_vars(9).orig_lead_lag = -8;
M_.aux_vars(10).endo_index = 62;
M_.aux_vars(10).type = 3;
M_.aux_vars(10).orig_index = 1;
M_.aux_vars(10).orig_lead_lag = -9;
M_.aux_vars(11).endo_index = 63;
M_.aux_vars(11).type = 3;
M_.aux_vars(11).orig_index = 1;
M_.aux_vars(11).orig_lead_lag = -10;
M_.aux_vars(12).endo_index = 64;
M_.aux_vars(12).type = 3;
M_.aux_vars(12).orig_index = 1;
M_.aux_vars(12).orig_lead_lag = -11;
M_.aux_vars(13).endo_index = 65;
M_.aux_vars(13).type = 3;
M_.aux_vars(13).orig_index = 1;
M_.aux_vars(13).orig_lead_lag = -12;
M_.aux_vars(14).endo_index = 66;
M_.aux_vars(14).type = 3;
M_.aux_vars(14).orig_index = 1;
M_.aux_vars(14).orig_lead_lag = -13;
M_.aux_vars(15).endo_index = 67;
M_.aux_vars(15).type = 3;
M_.aux_vars(15).orig_index = 1;
M_.aux_vars(15).orig_lead_lag = -14;
M_.aux_vars(16).endo_index = 68;
M_.aux_vars(16).type = 3;
M_.aux_vars(16).orig_index = 1;
M_.aux_vars(16).orig_lead_lag = -15;
M_.aux_vars(17).endo_index = 69;
M_.aux_vars(17).type = 3;
M_.aux_vars(17).orig_index = 1;
M_.aux_vars(17).orig_lead_lag = -16;
M_.aux_vars(18).endo_index = 70;
M_.aux_vars(18).type = 3;
M_.aux_vars(18).orig_index = 1;
M_.aux_vars(18).orig_lead_lag = -17;
M_.aux_vars(19).endo_index = 71;
M_.aux_vars(19).type = 3;
M_.aux_vars(19).orig_index = 1;
M_.aux_vars(19).orig_lead_lag = -18;
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('news_SW03_static');
erase_compiled_function('news_SW03_dynamic');
M_.orig_eq_nbr = 52;
M_.eq_nbr = 71;
M_.ramsey_eq_nbr = 0;
M_.lead_lag_incidence = [
 0 36 0;
 0 37 0;
 0 38 107;
 0 39 0;
 0 40 108;
 0 41 109;
 1 42 0;
 2 43 110;
 0 44 0;
 0 45 0;
 0 46 111;
 0 47 0;
 0 48 0;
 3 49 112;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 113;
 0 56 0;
 0 57 114;
 0 58 115;
 4 59 0;
 5 60 116;
 0 61 0;
 0 62 0;
 6 63 117;
 7 64 118;
 8 65 119;
 0 66 0;
 0 67 0;
 0 68 0;
 9 69 0;
 0 70 0;
 10 71 0;
 11 72 0;
 0 73 0;
 12 74 120;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 13 84 0;
 14 85 0;
 15 86 0;
 16 87 0;
 17 88 0;
 18 89 0;
 19 90 0;
 20 91 0;
 21 92 0;
 22 93 0;
 23 94 0;
 24 95 0;
 25 96 0;
 26 97 0;
 27 98 0;
 28 99 0;
 29 100 0;
 30 101 0;
 31 102 0;
 32 103 0;
 33 104 0;
 34 105 0;
 35 106 0;]';
M_.nstatic = 29;
M_.nfwrd   = 7;
M_.npred   = 28;
M_.nboth   = 7;
M_.nsfwrd   = 14;
M_.nspred   = 35;
M_.ndynamic   = 42;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(71, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(41, 1);
M_.NNZDerivatives = [206; -1; -1];
M_.params( 1 ) = 0.3;
calfa = M_.params( 1 );
M_.params( 2 ) = 0.025;
ctou = M_.params( 2 );
M_.params( 3 ) = 0.99;
cbeta = M_.params( 3 );
M_.params( 4 ) = 0.0;
chab = M_.params( 4 );
M_.params( 5 ) = 0.6;
ccs = M_.params( 5 );
M_.params( 6 ) = 0.22;
cinvs = M_.params( 6 );
M_.params( 7 ) = 6.7711;
csadjcost = M_.params( 7 );
M_.params( 8 ) = 1.3533;
csigma = M_.params( 8 );
M_.params( 9 ) = 0.5732;
chabb = M_.params( 9 );
M_.params( 10 ) = 0.7367;
cprobw = M_.params( 10 );
M_.params( 11 ) = 1.5;
clandaw = M_.params( 11 );
M_.params( 12 ) = 2.3995;
csigl = M_.params( 12 );
M_.params( 13 ) = 0.9082;
cprobp = M_.params( 13 );
M_.params( 14 ) = 0.7627;
cindw = M_.params( 14 );
M_.params( 15 ) = 0.4694;
cindp = M_.params( 15 );
M_.params( 16 ) = 1.4077;
cfc = M_.params( 16 );
M_.params( 17 ) = 1;
cinvdyn = M_.params( 17 );
M_.params( 18 ) = 0.1690;
czcap = M_.params( 18 );
M_.params( 19 ) = 0.5990;
csadjlab = M_.params( 19 );
M_.params( 20 ) = 1.6841;
crpi = M_.params( 20 );
M_.params( 21 ) = 0.1398;
crdpi = M_.params( 21 );
M_.params( 22 ) = 0.9613;
crr = M_.params( 22 );
M_.params( 23 ) = 0.0988;
cry = M_.params( 23 );
M_.params( 24 ) = 0.1586;
crdy = M_.params( 24 );
M_.params( 25 ) = 0.8232;
crhoa = M_.params( 25 );
M_.params( 26 ) = 0.9238;
crhoas = M_.params( 26 );
M_.params( 27 ) = 0.8545;
crhob = M_.params( 27 );
M_.params( 28 ) = 0.9493;
crhog = M_.params( 28 );
M_.params( 29 ) = 0.8894;
crhols = M_.params( 29 );
M_.params( 30 ) = 0.9273;
crhoqs = M_.params( 30 );
M_.params( 31 ) = 0.5978;
cscaleea = M_.params( 31 );
M_.params( 32 ) = 0.0165;
cscaleeas = M_.params( 32 );
M_.params( 33 ) = 0.3361;
cscaleeb = M_.params( 33 );
M_.params( 34 ) = 0.3247;
cscaleeg = M_.params( 34 );
M_.params( 35 ) = 3.5197;
cscaleels = M_.params( 35 );
M_.params( 36 ) = 0.0851;
cscaleeqs = M_.params( 36 );
M_.params( 37 ) = 0.0808;
cscaleem = M_.params( 37 );
M_.params( 38 ) = 0.6043;
cscaleeinv = M_.params( 38 );
M_.params( 39 ) = 0.1602;
cscaleepinf = M_.params( 39 );
M_.params( 40 ) = 0.2892;
cscaleew = M_.params( 40 );
M_.params( 41 ) = 0.081;
cscaleer = M_.params( 41 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 40;
options_.order = 1;
options_.periods = 0;
var_list_ = char();
info = stoch_simul(var_list_);
save('news_SW03_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('news_SW03_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('news_SW03_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('news_SW03_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('news_SW03_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('news_SW03_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('news_SW03_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
