addpath( '../FigureUtils' );

disp( 'We start by showing two solutions following the combination of shocks most likely to take the model to the ZLB.' );

disp( 'First, the solution which escapes the bound earliest.' );

dynareOBC SW07IRF.mod

Titles = { 'Output', 'Consumption', 'Inflation', 'Nom. int. rates' };
PrepareFigure( 26, Titles );
SaveFigure( [ 0.5, 1 ], 'Solution0' );

disp( 'Now we will see an alternative solution following the same shock which stays at the bound for much longer' );
disp( 'Press a key to continue:' );
pause;

dynareOBC SW07IRF.mod SkipFirstSolutions=1 TimeToEscapeBounds=41 % Manually setting TimeToEscapeBounds purely for the sake of the M diagonal plot.

Titles = { 'Output', 'Consumption', 'Inflation', 'Nom. int. rates' };
PrepareFigure( 26, Titles );
SaveFigure( [ 0.5, 1 ], 'Solution1' );

disp( 'Observe the severe recession generated by the longer spell at the ZLB.' );
disp( 'Press a key to continue:' );
pause;

disp( 'The multiplicity here is less obvious given that the diagonal of the M matrix is positive.' );
disp( 'The next figure shows this diagonal.' );

GenerateMDiagonalPlot;

Titles = { 'The Smets & Wouters (2003) model', 'The Smets & Wouters (2007) model' };
PrepareFigure( 26, Titles );
SaveFigure( [ 1, 1 ], 'SW03SW07DiagonalComparison' );
